apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiskagents.fullname" . }}-orchestrator-secrets
  labels:
    {{- include "aiskagents.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }} 