apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiskagents.fullname" . }}-orchestrator
  labels:
    {{- include "aiskagents.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  replicas: {{ .Values.orchestrator.replicaCount }}
  selector:
    matchLabels:
      {{- include "aiskagents.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/orchestrator-secrets.yaml") . | sha256sum }}
      labels:
        {{- include "aiskagents.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: orchestrator
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.orchestrator.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.orchestrator.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.orchestrator.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.orchestrator.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.orchestrator.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.orchestrator.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.orchestrator.probes.readiness.periodSeconds }}
          env:
            {{- range $key, $value := .Values.orchestrator.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- with .Values.orchestrator.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.orchestrator.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: mcp-cache
              mountPath: /home/orchestrator/.mcp-auth
      volumes:
        - name: tmp
          emptyDir: {}
        - name: mcp-cache
          emptyDir: {} 