version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app  # Optional: Mount the backend code for development
    environment:
      - ALLOWED_ORIGINS=*
      # For production, you might specify:
      # - ALLOWED_ORIGINS=https://yourdomain.com
      # The environment below so the backend can find Redis in Docker:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./frontend/sales-agent-crew
      dockerfile: Dockerfile
      args:
        VITE_API_URL: '/api'
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/sn-certs:/etc/sn-certs
    environment:
      - USE_OFFICIAL_CERTS=${USE_OFFICIAL_CERTS:-false}
    networks:
      - app-network
    depends_on:
      - backend

  redis:
    image: "redis:7.0-alpine"
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge
