version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app  # Optional: Mount the backend code for development

  frontend:
    build:
      context: ./frontend/sales-agent-crew
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        # VITE_CLERK_FRONTEND_API: ${VITE_CLERK_FRONTEND_API}
        # VITE_CLERK_DOMAIN: ${VITE_CLERK_DOMAIN}
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge 