version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app  # Optional: Mount the backend code for development
    environment:
      - ALLOWED_ORIGINS=* # For development/testing
      # For production, you might want to specify domains:
      # - ALLOWED_ORIGINS=https://yourdomain.com,https://api.yourdomain.com

  frontend:
    build:
      context: ./frontend/sales-agent-crew
      dockerfile: Dockerfile
      args:
        VITE_API_URL: '/api'
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        # VITE_CLERK_FRONTEND_API: ${VITE_CLERK_FRONTEND_API}
        # VITE_CLERK_DOMAIN: ${VITE_CLERK_DOMAIN}
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge 