# Enable LocalPV HostPath for basic storage
localpv-provisioner:
  enabled: true
  basePath: "/var/openebs/local"
  rbac:
    create: true

# Configure storage engines
engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false

# Mayastor configuration
mayastor:
  nodeSelector:
    kubernetes.io/arch: "amd64"
    storage: "true"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  csi:
    node:
      initContainers:
        enabled: true
      kubeletDir: "/var/lib/kubelet"
  etcd:
    clusterDomain: "cluster.local"
    persistence:
      enabled: true
      storageClass: "openebs-hostpath"
      size: "2Gi"
      mountPath: "/data"
    nodeSelector:
      kubernetes.io/arch: "amd64"
      storage: "true"

  io_engine:
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
        hugepages-2Mi: 1024Mi
      limits:
        cpu: 1000m
        memory: 512Mi
        hugepages-2Mi: 1024Mi
    nodeSelector:
      kubernetes.io/arch: "amd64"
      storage: "true"

    cpuCount: "2"
    coreList: ["0", "1"]

# Enable CSI volume snapshots
openebs-crds:
  csi:
    volumeSnapshots:
      enabled: true
      keep: true

loki:
  enabled: false